appname: homepage
replicas: 1

ingress:
  enabled: true
  routes:
    - match: 
        - homepage.local.imrein.com
      kind: Rule
      services:
        - name: homepage-service
          port: 80
      middlewares:
        - name: default-headers
  tls:
    secret: prod-imrein-com-live-tls
