appname: ntfy
replicas: 1

ingress:
  enabled: true
  routes:
    - match: 
        - ntfy.imrein.com
      kind: Rule
      services:
        - name: ntfy-service
          port: 80
      middlewares:
        - name: default-headers
  tls:
    secret: prod-imrein-com-live-tls
