---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: prod
  name: vault-auth
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  namespace: prod
  name: vault-connection
spec:
  # address to the Vault server.
  address: https://192.168.129.175:8200
  skipTLSVerify: true
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  namespace: prod
  name: vault-auth
spec:
  vaultConnectionRef: vault-connection
  method: kubernetes
  mount: vso
  kubernetes:
    role: vso-role
    serviceAccount: vault-auth
