---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: default
  name: vault-auth
---
apiVersion: v1
kind: Secret
metadata:
  namespace: default
  name: vault-auth
  annotations:
    kubernetes.io/service-account.name: vault-auth
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  namespace: default
  name: role-tokenreview-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: vault-auth
    namespace: default
  - kind: ServiceAccount
    name: vault-auth
    namespace: cert-manager
  - kind: ServiceAccount
    name: vault-auth
    namespace: longhorn-system
  - kind: ServiceAccount
    name: vault-auth
    namespace: traefik
  - kind: ServiceAccount
    name: vault-auth
    namespace: dev
  - kind: ServiceAccount
    name: vault-auth
    namespace: prod
