---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: traefik
  name: vault-auth
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  namespace: traefik
  name: vault-connection
spec:
  # address to the Vault server.
  address: https://192.168.129.175:8200
  skipTLSVerify: true
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  namespace: traefik
  name: vault-auth
spec:
  vaultConnectionRef: vault-connection
  method: kubernetes
  mount: vso
  kubernetes:
    role: vso-role
    serviceAccount: vault-auth
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  namespace: traefik
  name: traefik-dashboard-auth
spec:
  vaultAuthRef: vault-auth
  mount: homelab-kube
  type: kv-v2
  path: traefik
  refreshAfter: 10s
  destination:
    create: true
    name: traefik-dashboard-auth
    transformation:
      excludeRaw: true
