argo-cd:
  configs:
    repositories:
      homelab-k3s:
        name: homelab-k3s
        type: git
        project: default
        url: git@192.168.129.170:homelab/homelab_k3s.git
      homelab-helm-charts:
        name: homelab-helm-charts
        type: git
        project: default
        url: git@192.168.129.170:homelab/homelab_helm-charts.git

    # General Argo CD configuration
    ## Ref: https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/argocd-cm.yaml
    cm:
      # -- Create the argocd-cm configmap for [declarative setup]
      create: true

      # -- Annotations to be added to argocd-cm configmap
      annotations: {}

      # -- The name of tracking label used by Argo CD for resource pruning
      application.instanceLabelKey: argocd.argoproj.io/instance

      # -- Enable logs RBAC enforcement
      ## Ref: https://argo-cd.readthedocs.io/en/latest/operator-manual/upgrading/2.3-2.4/#enable-logs-rbac-enforcement
      server.rbac.log.enforce.enable: false

      # -- Enable exec feature in Argo UI
      ## Ref: https://argo-cd.readthedocs.io/en/latest/operator-manual/rbac/#exec-resource
      exec.enabled: false

      # -- Enable local admin user
      ## Ref: https://argo-cd.readthedocs.io/en/latest/faq/#how-to-disable-admin-user
      admin.enabled: true

      # -- Timeout to discover if a new manifests version got published to the repository
      timeout.reconciliation: 180s

      # -- Timeout to refresh application data as well as target manifests cache
      timeout.hard.reconciliation: 0s

      # -- Enable Status Badge
      ## Ref: https://argo-cd.readthedocs.io/en/stable/user-guide/status-badge/
      statusbadge.enabled: false
