appname: speedtest
replicas: 1
image:
  repository: henrywhitaker3/speedtest-tracker
  version: latest

service:
  name: speedtest-service
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80

ingress:
  enabled: true
  routes:
    - match: 
        - speedtest.local.imrein.com
      kind: Rule
      services:
        - name: speedtest-service
          port: 80
      middlewares:
        - name: default-headers
  tls:
    secret: local-imrein-com-live-tls

env:
  - name: OOKLA_EULA_GDPR
    value: "true"

resources:
  limits:
    memory: 150Mi
  requests:
    memory: 150Mi

pvc:
  enabled: true
  size: 2Gi

volumes:
  - name: speedtest
    type: block
    mountPath: /config
    subPath: config
