appname: speedtest
replicas: 1

ingress:
  enabled: true
  routes:
    - match: 
        - speedtest.dev.imrein.com
      kind: Rule
      services:
        - name: speedtest-service
          port: 80
      middlewares:
        - name: default-headers
  tls:
    secret: dev-imrein-com-live-tls
