{{- define "lib.configmap" }}
{{- if .Values.volumes }}
{{- range .Values.volumes }}
{{- if eq .type "configMap" }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .name }}-config
  labels:
    app.kubernetes.io/name: {{ .name }}
data:
  {{- with .data }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}