{{- define "lib.ingress" }}
{{- if .Values.ingress.enabled -}}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Values.appname }}-ingress
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  {{- if .Values.ingress.tls }}
  tls:
    secretName: {{ .Values.ingress.tls.secret }}
  {{- end }}
  routes:
    {{- range .Values.ingress.routes }}
    - match: {{ range $index, $host := .match }}{{ if $index }} || {{ end }}Host(`{{ $host }}`){{ end }}
      kind: Rule
      services:
        {{- range .services }}
        - name: {{ .name }}
          port: {{ .port }}
        {{- end }}
      middlewares:
        {{- range .middlewares }}
        - name: {{ .name }}
          namespace: default
        {{- end }}
    {{- end }}
{{- end }}
{{- end }}