{{- define "lib.serviceaccount" }}
{{- if .Values.serviceAccounts -}}
{{- range .Values.serviceAccounts }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .name }}
  labels:
    app.kubernetes.io/name: {{ .name }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: {{ .secret }}
  labels:
    app.kubernetes.io/name: {{ .secret }}
  annotations:
    kubernetes.io/service-account.name: {{ .name }}
{{- end }}
{{- end }}
{{- end }}