{{- define "lib.vaultstaticsecret" }}
{{- if .Values.secrets -}}
{{- range .Values.secrets }}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vss-{{ .name }}
spec:
  vaultAuthRef: vault-auth
  mount: homelab-kube
  type: kv-v2
  path: {{ .path }}
  refreshAfter: 10s
  destination:
    create: true
    name: {{ .name }}-secret
{{- end }}
{{- end }}
{{- end }}