---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: x@gmail.com
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - dns01:
          cloudflare:
            email: x@gmail.com
            apiTokenSecretRef:
              name: cloudflare-api-key
              key: api-key
        selector:
          dnsZones:
            - "imrein.com"
