prometheus:
  server:
    nodeSelector:
      worker: "true"
    service:
      enabled: true
      type: LoadBalancer
      servicePort: 80
    persistentVolume:
      enabled: true
      accessModes:
        - ReadWriteOnce
      size: 12Gi

  serverFiles:
    prometheus.yml:
      scrape_configs:
        - job_name: 'kubernetes-nodes-cadvisor'
          kubernetes_sd_configs:
            - role: pod
          relabel_configs:
            - source_labels: [__meta_kubernetes_pod_node_name]
              target_label: instance
          metric_relabel_configs:
            # Drop some metrics
            - source_labels: [__name__]
              regex: 'kube_(endpoint|lease|secret|service|container_fs|container_network)_.*'
              action: drop
            # Drop some pod metrics
            - source_labels: [__name__]
              regex: 'kube_(pod_ips|kube_pod_status_qos|kube_pod_status_scheduled|kube_pod_tolerations|kube_pod_owner|kube_pod_service_account)_.*'
              action: drop

  prometheus-node-exporter:
    service:
      enabled: true
      ## Service type
      type: LoadBalancer
      ## Default service port. Sets the port of the exposed container as well (NE or kubeRBACProxy).
      ## Use "servicePort" below if changing the service port only is desired.
      port: 9100
      ## Service port. Use this field if you wish to set a different service port
      ## without changing the container port ("port" above).
      servicePort: ""
      ## Targeted port in the pod. Must refer to an open container port ("port" or "portName").
      ## (IntOrString)
      targetPort: 9100
      ## Name of the service port. Sets the port name of the main container (NE) as well.
      portName: metrics
      ## Port number for service type NodePort
      nodePort: null

  kube-state-metrics:
    service:
      enabled: true
      ## Service type
      type: LoadBalancer
      ## Default service port. Sets the port of the exposed container as well (NE or kubeRBACProxy).
      ## Use "servicePort" below if changing the service port only is desired.
      port: 8080
      ## Service port. Use this field if you wish to set a different service port
      ## without changing the container port ("port" above).
      servicePort: ""
      ## Targeted port in the pod. Must refer to an open container port ("port" or "portName").
      ## (IntOrString)
      targetPort: 8080
      ## Port number for service type NodePort
      nodePort: null

  alertmanager:
    enabled: false
  prometheus-pushgateway:
    enabled: false
