appname: uptime-kuma
replicas: 1

ingress:
  enabled: true
  routes:
    - match: 
        - kuma.local.imrein.com
      kind: Rule
      services:
        - name: uptime-kuma-service
          port: 80
      middlewares:
        - name: default-headers
  tls:
    secret: prod-imrein-com-live-tls
