appname: stirlingpdf
replicas: 1

ingress:
  enabled: true
  routes:
    - match: 
        - pdf.dev.imrein.com
      kind: Rule
      services:
        - name: stirlingpdf-service
          port: 80
      middlewares:
        - name: default-headers
  tls:
    secret: dev-imrein-com-live-tls
