appname: website-blog
replicas: 2

ingress:
  enabled: true
  routes:
    - match: 
        - blog.dev.imrein.com
      kind: Rule
      services:
        - name: website-blog-service
          port: 80
      middlewares:
        - name: default-headers
        - name: headers-forwarding
  tls:
    secret: dev-imrein-com-live-tls
