---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: local-imrein-com
  namespace: default
spec:
  secretName: local-imrein-com-live-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.local.imrein.com"
  dnsNames:
  - "local.imrein.com"
  - "*.local.imrein.com"
