traefik:
  globalArguments:
    - "--global.sendanonymoususage=false"
    - "--global.checknewversion=false"

  additionalArguments:
    - "--serversTransport.insecureSkipVerify=true"
    - "--log.level=INFO"
    - "--providers.kubernetescrd.allowCrossNamespace=true"

  deployment:
    enabled: true
    replicas: 4
    annotations: {}
    podAnnotations: {}
    additionalContainers: []
    initContainers: []

  nodeSelector:
    node-role.kubernetes.io/master: "true"

  ports:
    web:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
      forwardedHeaders:
        trustedIPs:
          - 192.168.128.1/32
          - 192.168.129.10/32
          - 10.0.0.0/8
    websecure:
      http3:
        enabled: true
      advertisedPort: 4443
      tls:
        enabled: true
      forwardedHeaders:
        trustedIPs:
          - 192.168.128.1/32
          - 192.168.129.10/32
          - 10.0.0.0/8

  ingressRoute:
    dashboard:
      enabled: false

  logs:
    general:
      level: "INFO"

  providers:
    kubernetesCRD:
      enabled: true
      ingressClass: traefik-external
      allowExternalNameServices: true
    kubernetesIngress:
      enabled: true
      allowExternalNameServices: true
      publishedService:
        enabled: false

  rbac:
    enabled: true

  service:
    enabled: true
    type: LoadBalancer
    annotations: {}
    labels: {}
    spec:
      loadBalancerIP: 192.168.129.221 # this should be an IP in the MetalLB range
      externalTrafficPolicy: Local
    loadBalancerSourceRanges: []
    externalIPs: []
